# -*- coding:UTF-8 -*-
# 默认生成执行init初始化不会添加该字段，导致会报错，需手动添加
"""'User增加新的字段'

Revision ID: d0a35a10500d
Revises: d25cfba27139
Create Date: 2019-05-28 11:12:33.413000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a35a10500d'
down_revision = 'd25cfba27139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
