# -*- coding:UTF-8 -*-
# 默认生成执行init初始化不会添加该字段，导致会报错，需手动添加
"""'posts_table'

Revision ID: d25cfba27139
Revises: 37e7f6789373
Create Date: 2019-05-28 10:10:48.186000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25cfba27139'
down_revision = '37e7f6789373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
